module _2

/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
/// By starting with 1 and 2, the first 10 terms will be:
/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
/// find the sum of the even-valued terms.

let Run() =
    let limit = 4000000

    let fibSeq = Seq.unfold (fun state -> 
        if snd state > limit then None 
        else Some(fst state + snd state, (snd state, fst state + snd state))) (1,1)

    let sum = Seq.fold (fun acc elem -> 
        if elem % 2 = 0 then acc + elem else acc) 0 fibSeq

    sprintf "Sum of the even-valued Fibonacci terms below four million: %d" sum