import sys
import os
import time
os.chdir(os.path.dirname(os.path.abspath(__file__))) 

###############################################################################
# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
###############################################################################

def distinct_powers(min, max):
	terms = set( a ** b for a in range(min, max + 1) for b in range(min, max + 1))
	return len(terms)


# Main:
start = time.clock()

count = distinct_powers(2, 100)
print("Distinct powers: {}".format(count))
print ("Time: {}".format(time.clock() - start))





