import sys
import os
import time
import timeit
os.chdir(os.path.dirname(os.path.abspath(__file__))) 

###############################################################################
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
###############################################################################

def sum_of_even_fibonacci_terms(max):
    i1 = 1
    i2 = 2
    sum = 2

    while i2 + i1 < max:
        i1, i2 = i2, i1 + i2

        if i2 % 2 == 0:
            sum += i2

    return sum


def main():
    print ("Sum: {}".format(sum_of_even_fibonacci_terms(4000000)))


def main_timed():
    print("Time: {0:.25f}".format(timeit.timeit('main()', 'from ' + os.path.splitext(os.path.basename(__file__))[0] + ' import main', number=1)))

if __name__ == "__main__":
    main_timed()