import sys
import os
import timeit
os.chdir(os.path.dirname(os.path.abspath(__file__))) 

###############################################################################
# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
###############################################################################

def distinct_powers(min, max):
    terms = set( a ** b for a in range(min, max + 1) for b in range(min, max + 1))
    return len(terms)


def main():
    count = distinct_powers(2, 100)
    print("Distinct powers: {}".format(count))
    

def main_timed():
    print("Time: {0:.25f}".format(timeit.timeit('main()', 'from ' + os.path.splitext(os.path.basename(__file__))[0] + ' import main', number=1)))

if __name__ == "__main__":
    main_timed()